@startuml

Class Ryu
Class Ken

Class MedidorDeVitalidad

Class Hadoken
Class Fuego

Class Arma
Class Personaje{
    +Kick()
    +Punch()
    +MoveRight()
    +MoveLeft()
    +MoveDown()
    +MoveUp()
    +receiveDamage(int damageAmount)
    +getHealth() : float
}

Ryu --|> Personaje
Ken --|> Personaje

Personaje "1" *-- "1" MedidorDeVitalidad

Hadoken --|> Arma
Fuego --|> Arma

Ken o-- "1" Hadoken
Ryu o-- "0..1" Fuego

@enduml